#This file was generated by MC-Build

scoreboard players set #ifelse mcb.internal 1
attribute @s attack_damage modifier remove base_attack_damage
execute if items entity @s weapon.mainhand wooden_axe run attribute @s attack_damage modifier add base_attack_damage 2 add_value
execute if items entity @s weapon.mainhand stone_axe run attribute @s attack_damage modifier add base_attack_damage 3 add_value
execute if items entity @s weapon.mainhand iron_axe run attribute @s attack_damage modifier add base_attack_damage 4 add_value
execute if items entity @s weapon.mainhand golden_axe run attribute @s attack_damage modifier add base_attack_damage 2 add_value
execute if items entity @s weapon.mainhand diamond_axe run attribute @s attack_damage modifier add base_attack_damage 5 add_value
execute if items entity @s weapon.mainhand netherite_axe run attribute @s attack_damage modifier add base_attack_damage 6 add_value