#This file was generated by MC-Build

execute at @s anchored eyes positioned ^ ^ ^ positioned ~ ~-0.1 ~ run function oldcombat:throw_offhand
tellraw @s {"color":"red","text":"Offhand is disabled. Your offhanded item(s) were dropped on the ground."}
item replace entity @s weapon.offhand with air