#This file was generated by MC-Build

tellraw @s "Old Combat Configuration"
execute if score SwordBlocking OldCombatSettings matches 1 run function oldcombat:zzz/1
execute if score SwordBlocking OldCombatSettings matches 0 run function oldcombat:zzz/2
execute if score DisableOffhand OldCombatSettings matches 1 run function oldcombat:zzz/3
execute if score DisableOffhand OldCombatSettings matches 0 run function oldcombat:zzz/4
execute if score DisableAttackCooldown OldCombatSettings matches 1 run function oldcombat:zzz/5
execute if score DisableAttackCooldown OldCombatSettings matches 0 run function oldcombat:zzz/6
execute if score OldToolDamage OldCombatSettings matches 1 run function oldcombat:zzz/7
execute if score OldToolDamage OldCombatSettings matches 0 run function oldcombat:zzz/8
tellraw @s [{text:"Critical hits while sprinting is currently not implemented. Use my other datapack, \"Sprinting Crits\", to enable critical hits while sprinting. You can find it at "},{text:"https://modrinth.com/datapack/sprinting-crits/",color:"aqua",click_event:{action:"open_url",url:"https://modrinth.com/datapack/sprinting-crits"}},"."]
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""