#This file was generated by MC-Build

scoreboard objectives add OldCombatSettings dummy
tellraw @a "Old Combat: Loading Default Settings"
scoreboard players set DisableOffhand OldCombatSettings 1
scoreboard players set DisableAttackCooldown OldCombatSettings 1
scoreboard players set SwordBlocking OldCombatSettings 1
scoreboard players set OldToolDamage OldCombatSettings 1