#This file was generated by MC-Build

scoreboard players set #ifelse mcb.internal 0
execute if score DisableAttackCooldown OldCombatSettings matches 1 run function oldcombat:zzz/9
execute if score #ifelse mcb.internal matches 0 run function oldcombat:zzz/10