#This file was generated by MC-Build

scoreboard players set #ifelse mcb.internal 0
execute if score OldToolDamage OldCombatSettings matches 1 if items entity @s weapon.mainhand #axes run function oldcombat:zzz/11
execute if score #ifelse mcb.internal matches 0 run function oldcombat:zzz/12