#This file was generated by MC-Build

# you can use MC-Build without its internal scoreboard but this will limit the available features
scoreboard objectives add mcb.internal dummy
tellraw @a "Loading Old Combat Datapack by AndrewGaming587"