#This file was generated by MC-Build

scoreboard players set #ifelse mcb.internal 0
execute if score SwordBlocking OldCombatSettings matches 1 if items entity @s weapon.mainhand #minecraft:swords[!blocks_attacks] run function oldcombat:zzz/13
execute if score #ifelse mcb.internal matches 0 if score SwordBlocking OldCombatSettings matches 0 run function oldcombat:zzz/14