#This file was generated by MC-Build

summon marker ^ ^ ^0.4 {Tags:["throw_marker"]}
summon marker ^ ^ ^ {Tags:["pos_marker"]}
execute as @n[tag=throw_marker] store result score throw_x Temp run data get entity @s Pos[0] 80
execute as @n[tag=throw_marker] store result score throw_y Temp run data get entity @s Pos[1] 250
execute as @n[tag=throw_marker] store result score throw_z Temp run data get entity @s Pos[2] 80
execute as @n[tag=pos_marker] store result score og_x Temp run data get entity @s Pos[0] 80
execute as @n[tag=pos_marker] store result score og_y Temp run data get entity @s Pos[1] 250
execute as @n[tag=pos_marker] store result score og_z Temp run data get entity @s Pos[2] 80
scoreboard players operation mx Temp = throw_x Temp
scoreboard players operation my Temp = throw_y Temp
scoreboard players operation mz Temp = throw_z Temp
scoreboard players operation mx Temp -= og_x Temp
scoreboard players operation my Temp -= og_y Temp
scoreboard players operation mz Temp -= og_z Temp
kill @e[tag=throw_marker]
kill @e[tag=pos_marker]
summon item ~ ~ ~ {Tags:["thrown"],Item:{id:"minecraft:stone",count:1,components:{}},PickupDelay:40s,Age:0}
data modify entity @n[tag=thrown,type=item] Thrower set from entity @s UUID
execute store result entity @n[tag=thrown,type=item] Motion[0] double 0.0125 run scoreboard players get mx Temp
execute store result entity @n[tag=thrown,type=item] Motion[1] double 0.004 run scoreboard players get my Temp
execute store result entity @n[tag=thrown,type=item] Motion[2] double 0.0125 run scoreboard players get mz Temp
execute if entity @s[type=player] run function oldcombat:zzz/16
execute unless entity @s[type=player] run function oldcombat:zzz/17
tag @n[tag=thrown,type=item] remove thrown